[build]
command = """\
  npm install sass-embedded-linux-x64@${DART_SASS_VERSION} && \
  mkdir -p /opt/build/repo/node_modules/.bin && \
  cp /opt/build/repo/node_modules/sass-embedded-linux-x64/dart-sass-embedded/dart-sass-embedded /opt/build/repo/node_modules/.bin && \
  dart-sass-embedded --version && \
  hugo -s prebuild && \
  hugo --gc --minify \
  """
publish = "public"

[build.environment]
DART_SASS_VERSION = "1.56.2"
HUGO_VERSION = "0.112.1"
TZ = "America/Los_Angeles"
