[build.environment]
DART_SASS_VERSION = "1.63.5"
HUGO_VERSION = "0.114.0"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  mkdir -p /opt/build/repo/node_modules/.bin && \
  cp -r dart-sass/* /opt/build/repo/node_modules/.bin && \
  rm -rf dart-sass* && \
  hugo -s prebuild && \
  hugo --gc --minify \
  """
